name: Salesforce Auth

on:
  workflow_dispatch:

jobs:
  jwt-auth:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Salesforce CLI
      run: npm install --global @salesforce/cli

    - name: Authenticate to Salesforce using JWT
      env:
        SF_CLIENT_ID: ${{ secrets.SF_CLIENT_ID }}
        SF_JWT_KEY: ${{ secrets.SF_JWT_KEY }}
        SF_USERNAME: ${{ secrets.SF_USERNAME }}
      run: |
        echo "$SF_JWT_KEY" > server.key
        sf org login jwt \
          --client-id $SF_CLIENT_ID \
          --jwt-key-file server.key \
          --username $SF_USERNAME \
          --alias my-org \
          --set-default
